version: 2.1

commands:
  cloudsmith_upload:
    description: "Unified Cloudsmith upload for all platforms"
    parameters:
      build_dir:
        type: string
      pkg_ext:
        type: string
        default: "gz"
    steps:
      - run:
          name: Cloudsmith upload
          command: |
            cd "$(git rev-parse --show-toplevel)"
            chmod +x ci/cloudsmith-upload.sh
            export BUILD_DIR="<< parameters.build_dir >>"
            export CLOUDSMITH_PKG_EXT="<< parameters.pkg_ext >>"
            ci/cloudsmith-upload.sh

jobs:

  linux-build:
    machine:
      image: ubuntu-2404:current
    steps:
      - checkout
      - run: ci/circleci-build-linux.sh
      - cloudsmith_upload:
          build_dir: "$PWD/artifacts/linux/package"
          pkg_ext: "gz"

  flatpak-build:
    machine:
      image: ubuntu-2404:current
    steps:
      - checkout
      - run: ci/circleci-build-flatpak.sh
      - cloudsmith_upload:
          build_dir: "$PWD/artifacts/flatpak-x86_64/package"
          pkg_ext: "gz"

  macos-build:
    macos:
      xcode: 15.0.0
    steps:
      - checkout
      - run: ci/circleci-build-macos.sh
      - cloudsmith_upload:
          build_dir: "$PWD/artifacts/macos-arm64/package"
          pkg_ext: "gz"

  android-arm64-build:
    machine:
      image: ubuntu-2404:current
    steps:
      - checkout
      - run: ci/circleci-build-android-arm64.sh
      - cloudsmith_upload:
          build_dir: "$PWD/artifacts/android-arm64/package"
          pkg_ext: "gz"

  android-armhf-build:
    machine:
      image: ubuntu-2404:current
    steps:
      - checkout
      - run: ci/circleci-build-android-armhf.sh
      - cloudsmith_upload:
          build_dir: "$PWD/artifacts/android-armhf/package"
          pkg_ext: "gz"

  windows-build:
    machine:
      image: windows-server-2022-gui:current
    steps:
      - checkout
      - run: ci/circleci-build-windows.ps1
      - cloudsmith_upload:
          build_dir: "$PWD/build"
          pkg_ext: "exe"

workflows:
  version: 2
  build_and_upload:
    jobs:
      - linux-build
      - flatpak-build
      - macos-build
      - android-arm64-build
      - android-armhf-build
      - windows-build
