#ifndef __weather_routing_piEditPolarDialogBase__
#define __weather_routing_piEditPolarDialogBase__

/**
@file
Subclass of EditPolarDialogBase, which is generated by wxFormBuilder.
*/

#include "WeatherRoutingUI.h"

//// end generated include

/** Implementing EditPolarDialogBase */
class weather_routing_piEditPolarDialogBase : public EditPolarDialogBase
{
	protected:
		// Handlers for EditPolarDialogBase events.
		void OnPolarGridChanged( wxGridEvent& event );
		void d( wxCommandEvent& event );
		void OnAddTrueWindAngle( wxCommandEvent& event );
		void OnRemoveTrueWindAngle( wxCommandEvent& event );
		void OnAddTrueWindSpeed( wxCommandEvent& event );
		void OnRemoveTrueWindSpeed( wxCommandEvent& event );
		void OnAddMeasurement( wxCommandEvent& event );
		void OnRemoveMeasurement( wxCommandEvent& event );
		void OnRemoveAllMeasurements( wxCommandEvent& event );
		void OnGeneratePolar( wxCommandEvent& event );
		void OnRecompute( wxCommandEvent& event );
		void OnRecomputeSpin( wxSpinEvent& event );
		void OnSave( wxCommandEvent& event );
	public:
		/** Constructor */
		weather_routing_piEditPolarDialogBase( wxWindow* parent );
	//// end generated class members

};

#endif // __weather_routing_piEditPolarDialogBase__
