#ifndef __weather_routing_piPlotDialogBase__
#define __weather_routing_piPlotDialogBase__

/**
@file
Subclass of PlotDialogBase, which is generated by wxFormBuilder.
*/

#include "WeatherRoutingUI.h"

//// end generated include

/** Implementing PlotDialogBase */
class weather_routing_piPlotDialogBase : public PlotDialogBase
{
	protected:
		// Handlers for PlotDialogBase events.
		void OnMouseEventsPlot( wxMouseEvent& event );
		void OnPaintPlot( wxPaintEvent& event );
		void OnSizePlot( wxSizeEvent& event );
		void OnUpdateUI( wxUpdateUIEvent& event );
		void OnUpdatePlot( wxScrollEvent& event );
		void OnUpdatePlotVariable( wxCommandEvent& event );
		void OnUpdateRoute( wxCommandEvent& event );
	public:
		/** Constructor */
		weather_routing_piPlotDialogBase( wxWindow* parent );
	//// end generated class members

};

#endif // __weather_routing_piPlotDialogBase__
