#ifndef __weather_routing_piWeatherRoutingBase__
#define __weather_routing_piWeatherRoutingBase__

/**
@file
Subclass of WeatherRoutingBase, which is generated by wxFormBuilder.
*/

#include "WeatherRoutingUI.h"

//// end generated include

/** Implementing WeatherRoutingBase */
class weather_routing_piWeatherRoutingBase : public WeatherRoutingBase
{
	protected:
		// Handlers for WeatherRoutingBase events.
		void OnClose( wxCloseEvent& event );
		void OnSize( wxSizeEvent& event );
		void OnOpen( wxCommandEvent& event );
		void OnSave( wxCommandEvent& event );
		void OnNewPosition( wxCommandEvent& event );
		void OnUpdateBoat( wxCommandEvent& event );
		void OnDeletePosition( wxCommandEvent& event );
		void OnDeleteAllPositions( wxCommandEvent& event );
		void OnNew( wxCommandEvent& event );
		void OnBatch( wxCommandEvent& event );
		void OnEditConfiguration( wxCommandEvent& event );
		void OnGoTo( wxCommandEvent& event );
		void OnDelete( wxCommandEvent& event );
		void OnDeleteAll( wxCommandEvent& event );
		void OnCompute( wxCommandEvent& event );
		void OnComputeAll( wxCommandEvent& event );
		void OnStop( wxCommandEvent& event );
		void OnResetAll( wxCommandEvent& event );
		void OnExport( wxCommandEvent& event );
		void OnExportAll( wxCommandEvent& event );
		void OnFilter( wxCommandEvent& event );
		void OnSettings( wxCommandEvent& event );
		void OnStatistics( wxCommandEvent& event );
		void OnReport( wxCommandEvent& event );
		void OnPlot( wxCommandEvent& event );
		void OnCursorPosition( wxCommandEvent& event );
		void OnRoutePosition( wxCommandEvent& event );
		void OnInformation( wxCommandEvent& event );
		void OnManual( wxCommandEvent& event );
		void OnAbout( wxCommandEvent& event );
	public:
		/** Constructor */
		weather_routing_piWeatherRoutingBase( wxWindow* parent );
	//// end generated class members

};

#endif // __weather_routing_piWeatherRoutingBase__
