#ifndef __weather_routing_piBoatDialogBase__
#define __weather_routing_piBoatDialogBase__

/**
@file
Subclass of BoatDialogBase, which is generated by wxFormBuilder.
*/

#include "WeatherRoutingUI.h"

//// end generated include

/** Implementing BoatDialogBase */
class weather_routing_piBoatDialogBase : public BoatDialogBase
{
	protected:
		// Handlers for BoatDialogBase events.
		void OnMouseEventsPolarPlot( wxMouseEvent& event );
		void OnPaintPlot( wxPaintEvent& event );
		void OnUpdatePlot( wxSizeEvent& event );
		void OnPaintCrossOverChart( wxPaintEvent& event );
		void OnOverlapPercentage( wxSpinEvent& event );
		void OnVMGWindSpeed( wxSpinEvent& event );
		void OnPolarSelected( wxListEvent& event );
		void OnUpPolar( wxCommandEvent& event );
		void OnDownPolar( wxCommandEvent& event );
		void OnEditPolar( wxCommandEvent& event );
		void OnAddPolar( wxCommandEvent& event );
		void OnRemovePolar( wxCommandEvent& event );
		void OnOpenBoat( wxCommandEvent& event );
		void OnSaveBoat( wxCommandEvent& event );
		void OnSaveAsBoat( wxCommandEvent& event );
	public:
		/** Constructor */
		weather_routing_piBoatDialogBase( wxWindow* parent );
	//// end generated class members

};

#endif // __weather_routing_piBoatDialogBase__
