#ifndef __weather_routing_piSettingsDialogBase__
#define __weather_routing_piSettingsDialogBase__

/**
@file
Subclass of SettingsDialogBase, which is generated by wxFormBuilder.
*/

#include "WeatherRoutingUI.h"

//// end generated include

/** Implementing SettingsDialogBase */
class weather_routing_piSettingsDialogBase : public SettingsDialogBase
{
	protected:
		// Handlers for SettingsDialogBase events.
		void OnUpdateColor( wxColourPickerEvent& event );
		void OnUpdateSpin( wxSpinEvent& event );
		void OnUpdate( wxCommandEvent& event );
		void OnUpdateColumns( wxCommandEvent& event );
		void OnHelp( wxCommandEvent& event );
	public:
		/** Constructor */
		weather_routing_piSettingsDialogBase( wxWindow* parent );
	//// end generated class members

};

#endif // __weather_routing_piSettingsDialogBase__
