#ifndef __weather_routing_piRoutePositionDialog__
#define __weather_routing_piRoutePositionDialog__

/**
@file
Subclass of RoutePositionDialog, which is generated by wxFormBuilder.
*/

#include "WeatherRoutingUI.h"

//// end generated include

/** Implementing RoutePositionDialog */
class weather_routing_piRoutePositionDialog : public RoutePositionDialog
{
	public:
		/** Constructor */
		weather_routing_piRoutePositionDialog( wxWindow* parent );
	//// end generated class members

};

#endif // __weather_routing_piRoutePositionDialog__
