#ifndef __weather_routing_piCursorPositionDialog__
#define __weather_routing_piCursorPositionDialog__

/**
@file
Subclass of CursorPositionDialog, which is generated by wxFormBuilder.
*/

#include "WeatherRoutingUI.h"

//// end generated include

/** Implementing CursorPositionDialog */
class weather_routing_piCursorPositionDialog : public CursorPositionDialog
{
	public:
		/** Constructor */
		weather_routing_piCursorPositionDialog( wxWindow* parent );
	//// end generated class members

};

#endif // __weather_routing_piCursorPositionDialog__
