#ifndef __weather_routing_piWeatherRoutingPanel__
#define __weather_routing_piWeatherRoutingPanel__

/**
@file
Subclass of WeatherRoutingPanel, which is generated by wxFormBuilder.
*/

#include "WeatherRoutingUI.h"

//// end generated include

/** Implementing WeatherRoutingPanel */
class weather_routing_piWeatherRoutingPanel : public WeatherRoutingPanel
{
	protected:
		// Handlers for WeatherRoutingPanel events.
		void OnEditPositionClick( wxMouseEvent& event );
		void OnLeftUp( wxMouseEvent& event );
		void OnLeftDown( wxMouseEvent& event );
		void OnPositionKeyDown( wxListEvent& event );
		void OnEditConfigurationClick( wxMouseEvent& event );
		void OnWeatherRoutesListLeftDown( wxMouseEvent& event );
		void OnWeatherRouteSort( wxListEvent& event );
		void OnWeatherRouteSelected( wxListEvent& event );
		void OnWeatherRouteKeyDown( wxListEvent& event );
		void OnCompute( wxCommandEvent& event );
		void OnExport( wxCommandEvent& event );
	public:
		/** Constructor */
		weather_routing_piWeatherRoutingPanel( wxWindow* parent );
	//// end generated class members

};

#endif // __weather_routing_piWeatherRoutingPanel__
