#ifndef __weather_routing_piAboutDialogBase__
#define __weather_routing_piAboutDialogBase__

/**
@file
Subclass of AboutDialogBase, which is generated by wxFormBuilder.
*/

#include "WeatherRoutingUI.h"

//// end generated include

/** Implementing AboutDialogBase */
class weather_routing_piAboutDialogBase : public AboutDialogBase
{
	protected:
		// Handlers for AboutDialogBase events.
		void OnAboutAuthor( wxCommandEvent& event );
		void OnClose( wxCommandEvent& event );
	public:
		/** Constructor */
		weather_routing_piAboutDialogBase( wxWindow* parent );
	//// end generated class members

};

#endif // __weather_routing_piAboutDialogBase__
