#ifndef __weather_routing_piConfigurationDialogBase__
#define __weather_routing_piConfigurationDialogBase__

/**
@file
Subclass of ConfigurationDialogBase, which is generated by wxFormBuilder.
*/

#include "WeatherRoutingUI.h"

//// end generated include

/** Implementing ConfigurationDialogBase */
class weather_routing_piConfigurationDialogBase : public ConfigurationDialogBase
{
	protected:
		// Handlers for ConfigurationDialogBase events.
		void OnUpdate( wxCommandEvent& event );
		void OnUpdateDate( wxDateEvent& event );
		void OnGribTime( wxCommandEvent& event );
		void OnUpdateTime( wxDateEvent& event );
		void OnCurrentTime( wxCommandEvent& event );
		void OnBoatFilename( wxCommandEvent& event );
		void OnEditBoat( wxCommandEvent& event );
		void EnableSpin( wxMouseEvent& event );
		void OnUpdateSpin( wxSpinEvent& event );
		void OnClose( wxCommandEvent& event );
		void OnAvoidCyclones( wxCommandEvent& event );
		void OnResetAdvanced( wxCommandEvent& event );
	public:
		/** Constructor */
		weather_routing_piConfigurationDialogBase( wxWindow* parent );
	//// end generated class members

};

#endif // __weather_routing_piConfigurationDialogBase__
