#ifndef __weather_routing_piConfigurationBatchDialogBase__
#define __weather_routing_piConfigurationBatchDialogBase__

/**
@file
Subclass of ConfigurationBatchDialogBase, which is generated by wxFormBuilder.
*/

#include "WeatherRoutingUI.h"

//// end generated include

/** Implementing ConfigurationBatchDialogBase */
class weather_routing_piConfigurationBatchDialogBase : public ConfigurationBatchDialogBase
{
	protected:
		// Handlers for ConfigurationBatchDialogBase events.
		void OnOnce( wxCommandEvent& event );
		void OnDaily( wxCommandEvent& event );
		void OnWeekly( wxCommandEvent& event );
		void OnMonthly( wxCommandEvent& event );
		void OnSources( wxCommandEvent& event );
		void OnDestinations( wxCommandEvent& event );
		void OnConnect( wxCommandEvent& event );
		void OnDisconnectAll( wxCommandEvent& event );
		void OnAddBoat( wxCommandEvent& event );
		void OnRemoveBoat( wxCommandEvent& event );
		void On100( wxCommandEvent& event );
		void On80to120( wxCommandEvent& event );
		void OnInformation( wxCommandEvent& event );
		void OnReset( wxCommandEvent& event );
		void OnGenerate( wxCommandEvent& event );
		void OnClose( wxCommandEvent& event );
	public:
		/** Constructor */
		weather_routing_piConfigurationBatchDialogBase( wxWindow* parent );
	//// end generated class members

};

#endif // __weather_routing_piConfigurationBatchDialogBase__
