#ifndef __weather_routing_piFilterRoutesDialogBase__
#define __weather_routing_piFilterRoutesDialogBase__

/**
@file
Subclass of FilterRoutesDialogBase, which is generated by wxFormBuilder.
*/

#include "WeatherRoutingUI.h"

//// end generated include

/** Implementing FilterRoutesDialogBase */
class weather_routing_piFilterRoutesDialogBase : public FilterRoutesDialogBase
{
	protected:
		// Handlers for FilterRoutesDialogBase events.
		void OnCategory( wxCommandEvent& event );
		void OnFilterText( wxCommandEvent& event );
		void OnResetAll( wxCommandEvent& event );
		void OnDone( wxCommandEvent& event );
	public:
		/** Constructor */
		weather_routing_piFilterRoutesDialogBase( wxWindow* parent );
	//// end generated class members

};

#endif // __weather_routing_piFilterRoutesDialogBase__
