#ifndef __weather_routing_piNewPositionDialog__
#define __weather_routing_piNewPositionDialog__

/**
@file
Subclass of NewPositionDialog, which is generated by wxFormBuilder.
*/

#include "WeatherRoutingUI.h"

//// end generated include

/** Implementing NewPositionDialog */
class weather_routing_piNewPositionDialog : public NewPositionDialog
{
	public:
		/** Constructor */
		weather_routing_piNewPositionDialog( wxWindow* parent );
	//// end generated class members

};

#endif // __weather_routing_piNewPositionDialog__
