#ifndef __weather_routing_piReportDialogBase__
#define __weather_routing_piReportDialogBase__

/**
@file
Subclass of ReportDialogBase, which is generated by wxFormBuilder.
*/

#include "WeatherRoutingUI.h"

//// end generated include

/** Implementing ReportDialogBase */
class weather_routing_piReportDialogBase : public ReportDialogBase
{
	protected:
		// Handlers for ReportDialogBase events.
		void OnInformation( wxCommandEvent& event );
		void OnClose( wxCommandEvent& event );
	public:
		/** Constructor */
		weather_routing_piReportDialogBase( wxWindow* parent );
	//// end generated class members

};

#endif // __weather_routing_piReportDialogBase__
