#ifndef __weather_routing_piStatisticsDialogBase__
#define __weather_routing_piStatisticsDialogBase__

/**
@file
Subclass of StatisticsDialogBase, which is generated by wxFormBuilder.
*/

#include "WeatherRoutingUI.h"

//// end generated include

/** Implementing StatisticsDialogBase */
class weather_routing_piStatisticsDialogBase : public StatisticsDialogBase
{
	public:
		/** Constructor */
		weather_routing_piStatisticsDialogBase( wxWindow* parent );
	//// end generated class members

};

#endif // __weather_routing_piStatisticsDialogBase__
